import Head from 'next/head';
import Layout from '../components/layout';
import { getAllPostIds } from '../../lib/post';
import { getPostData } from '../../lib/post';
import Profile from '../components/profile';
import { BookmarkIcon } from '@heroicons/react/outline';

export async function getStaticPaths() {
	const paths = getAllPostIds();
	return {
		paths,
		fallback: false,
	};
}

export async function getStaticProps({ params }) {
	const post = await getPostData(params.id);
	return {
		props: {
			post,
		},
	};
}

export default function Post({ post }) {
	return (
		<Layout>
			<Head>
				<title> {post.title} </title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='flex flex-wrap items-start gap-10 xl:flex-nowrap'>
				<Profile></Profile>
				<div className='w-full rounded-lg bg-white p-10 xl:w-3/4'>
					<div className='item flex w-full justify-between border-b border-slate-100 pb-4'>
						<div className='w-9/10'>
							<h1 className='text-xl font-bold text-slate-900'>{post.title}</h1>
							<p className='text-md font-semibold text-sky-500'>{post.date}</p>
						</div>
						<div className='w-1/10 p-1'>
							<BookmarkIcon className='h-5 w-5 text-sky-500' />
						</div>
					</div>
					<p
						dangerouslySetInnerHTML={{ __html: post.body }}
						className='pt-6 text-justify leading-8 text-slate-500'
					/>
					<div className='flex gap-2 pt-4'>
						<p className='rounded-full bg-sky-100 py-2 px-4 text-xs text-sky-500'>#programming</p>
						<p className='rounded-full bg-sky-100 py-2 px-4 text-xs text-sky-500'>#nextjs</p>
					</div>
				</div>
			</div>
		</Layout>
	);
}
