import Link from 'next/link';
import Head from 'next/head';
import Image from 'next/image';
import Script from 'next/script';
import Layout from '../components/layout';

export default function FirstPost() {
	return (
		<Layout>
			<div className='flex flex-col items-start justify-center pt-[20vh]'>
				<div className='mx-auto w-full rounded-lg bg-white px-4 py-10 shadow-lg shadow-slate-300/10 lg:px-20 xl:w-1/2'>
					<Head>
						<title> Next App Post </title>{' '}
						<meta name='description' content='Generated by create next app' />
						<link rel='icon' href='/favicon.ico' />
					</Head>
					<Script
						src='https://connect.facebook.net/en_US/sdk.js'
						strategy='lazyOnload'
						onLoad={() => console.log(`script loaded correctly, window.FB has been populated`)}
					/>
					<div className='flex items-center justify-start gap-4'>
						<Image src='/images/avatar.png' alt='avatar' height={48} width={48} />
						<div className='flex flex-col'>
							<span className='text-lg font-semibold'>Hidayattul Rafli</span>
							<p className='text-sm text-slate-600'>Software Engineer</p>
						</div>
					</div>
					<h1 className='mt-10 text-3xl font-bold text-slate-900'>Hello World</h1>
					<p className='mt-4 text-justify leading-8 text-slate-600'>
						Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem, aliquid. Earum, recusandae
						aspernatur sapiente eos adipisci temporibus quisquam molestiae sit molestias excepturi corporis
						ratione modi quas commodi rerum fugit neque perferendis quibusdam minima nihil esse voluptatem
						ab ipsa. Tempore unde fugit accusantium corrupti dolores dolorem eius recusandae distinctio
						voluptatem dignissimos!
					</p>
					<Link href='/' passHref>
						<a className='mt-4 inline-block rounded-md bg-slate-800 px-3 py-2 text-white'>Menu</a>
					</Link>
				</div>
			</div>
		</Layout>
	);
}
