import Link from 'next/link';
import Head from 'next/head';
import Image from 'next/image';
import Script from 'next/script';
import Layout from '../components/layout';
import { getSortedPostData } from '../../lib/post';
import { BookmarkIcon } from '@heroicons/react/outline';

export async function getStaticProps() {
	const allpost = getSortedPostData();
	return {
		props: {
			allpost,
		},
	};
}

export default function FirstPost({ allpost }) {
	return (
		<Layout>
			<div className='flex flex-wrap items-start gap-10 xl:flex-nowrap'>
				<div className='w-full rounded-lg bg-white p-10 xl:w-1/4'>
					<Head>
						<title> Next App Post </title>
						<meta name='description' content='Generated by create next app' />
						<link rel='icon' href='/favicon.ico' />
					</Head>
					<div className='flex items-center justify-start gap-4'>
						<Image src='/images/avatar.png' alt='avatar' height={48} width={48} />
						<div className='flex flex-col'>
							<span className='text-lg font-bold'>Hidayattul Rafli</span>
							<p className='text-sm font-semibold text-sky-500'>Software Engineer</p>
						</div>
					</div>
					<h1 className='mt-10 text-lg font-bold text-slate-900'>Hello World</h1>
					<p className='mt-4 leading-8 text-slate-500'>
						<span className='font-bold'>Lorem ipsum </span>dolor sit amet consectetur adipisicing elit. Rem,
						aliquid. Earum, corporis ratione modi quas commodi rerum fugit neque perferendis quibusdam
						minima nihil esse voluptatem ab ipsa.{' '}
						<span className='font-bold underline decoration-sky-500 decoration-dotted decoration-2 underline-offset-2'>
							Tempore unde fugit accusantium corrupti
						</span>
						dolores dolorem eius recusandae distinctio voluptatem dignissimos!
					</p>
				</div>
				<div className='w-full xl:w-3/4'>
					<div className='w-full rounded-lg bg-white p-6'>
						<h1 className='text-lg font-bold'>All Post</h1>
					</div>
					<div className='mt-10 grid w-full grid-cols-1 flex-wrap items-start gap-8 md:grid-cols-2 lg:grid-cols-3'>
						{console.log(allpost)}
						{allpost.map((post) => (
							<div key='id' className='w-full rounded-lg bg-white p-6'>
								<div className='item flex w-full justify-between border-b border-slate-100 pb-4'>
									<div className='w-9/10'>
										<h1 className='text-lg font-bold text-slate-900'>{post.title}</h1>
										<p className='text-sm font-semibold text-sky-500'>{post.date}</p>
									</div>
									<div className='w-1/10 p-1'>
										<BookmarkIcon className='h-5 w-5 text-sky-500' />
									</div>
								</div>
								<div className='pt-4 text-slate-500'>
									<p>
										A group of people interested in dogecoin, the currency and a bit of side for the
										meme and dof that we all know and love. These cases are perfectly simple and
										easy to distinguish.
									</p>
									<div className='flex gap-2 pt-4'>
										<p className='rounded-full bg-sky-100 py-2 px-4 text-xs text-sky-500'>
											#dogecoin
										</p>
										<p className='rounded-full bg-sky-100 py-2 px-4 text-xs text-sky-500'>
											#crypto
										</p>
									</div>
								</div>
							</div>
						))}
					</div>
				</div>
			</div>
		</Layout>
	);
}
