import Link from 'next/link';
import Head from 'next/head';
import Image from 'next/image';
import Layout from '../components/layout';
import { getSortedPostData } from '../../lib/post';
import { BookmarkIcon } from '@heroicons/react/outline';
import Profile from '../components/profile';

export async function getStaticProps() {
	const allpost = getSortedPostData();
	return {
		props: {
			allpost,
		},
	};
}

export default function FirstPost({ allpost }) {
	return (
		<Layout>
			<div className='flex flex-wrap items-start gap-10 xl:flex-nowrap'>
				<Head>
					<title> Next App Post </title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/favicon.ico' />
				</Head>
				<Profile></Profile>
				<div className='w-full xl:w-3/4'>
					<div className='w-full rounded-lg bg-white p-6'>
						<h1 className='text-lg font-bold'>All Post</h1>
					</div>
					<div className='mt-10 grid w-full grid-cols-1 flex-wrap items-start gap-8 md:grid-cols-2 lg:grid-cols-3'>
						{allpost.map((post) => (
							<Link href={`/post/${post.id}`} key='id' passHref>
								<a href='#' className='transition-transform ease-in-out hover:scale-[1.03]'>
									<div className='w-full rounded-lg bg-white p-6'>
										<div className='item flex w-full justify-between border-b border-slate-100 pb-4'>
											<div className='w-9/10'>
												<h1 className='text-lg font-bold text-slate-900'>{post.title}</h1>
												<p className='text-md font-semibold text-sky-500'>{post.date}</p>
											</div>
											<div className='w-1/10 p-1'>
												<BookmarkIcon className='h-5 w-5 text-sky-500' />
											</div>
										</div>
										<div className='pt-4 text-slate-500'>
											<p>
												A group of people interested in dogecoin, the currency and a bit of side
												for the meme and dof that we all know and love. These cases are
												perfectly simple and easy to distinguish.
											</p>
											<div className='flex gap-2 pt-4'>
												<p className='rounded-full bg-sky-100 py-2 px-4 text-xs text-sky-500'>
													#programming
												</p>
												<p className='rounded-full bg-sky-100 py-2 px-4 text-xs text-sky-500'>
													#nextjs
												</p>
											</div>
										</div>
									</div>
								</a>
							</Link>
						))}
					</div>
				</div>
			</div>
		</Layout>
	);
}
