import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import Layout from './components/layout';

export default function Home() {
	return (
		<Layout>
			<Head>
				<title> Create Next App </title> <meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<h1 className={(styles.title, 'text-6xl font-bold')}>
					Learn{' '}
					<a href='https://nextjs.org' className='text-blue-500 underline-offset-4 hover:underline'>
						Next.js!
					</a>
				</h1>
				<p className={styles.description}>
					Get started by editing <code className={styles.code}> pages / index.js </code>
				</p>
				<div className={styles.grid}>
					<a href='https://nextjs.org/docs' className={styles.card}>
						<h2> Documentation </h2>
						<p> Find in -depth information about Next.js features and API. </p>
					</a>
					<a href='https://nextjs.org/learn' className={styles.card}>
						<h2> Learn </h2> <p> Learn about Next.js in an interactive course with quizzes! </p>
					</a>
					<a href='https://github.com/vercel/next.js/tree/canary/examples' className={styles.card}>
						<h2> Examples </h2> <p> Discover and deploy boilerplate example Next.js projects. </p>
					</a>
					<a
						href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
						className={styles.card}>
						<h2> Deploy </h2>
						<p> Instantly deploy your Next.js site to a public URL with Vercel. </p>
					</a>
				</div>
				<Link href='/post/first-post' passHref>
					<a className='bg-blue mt-4 inline-block rounded-md bg-slate-800 px-3 py-2 text-white'>
						Explore Post
					</a>
				</Link>
			</main>
		</Layout>
	);
}
